Traceback (most recent call last):
  File "/home/enrico/UiS/DNN/CHESS/main.py", line 15, in <module>
    wandb.log(
  File "/home/enrico/UiS/DNN/CHESS/FinalProjectVenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 452, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/enrico/UiS/DNN/CHESS/FinalProjectVenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/enrico/UiS/DNN/CHESS/FinalProjectVenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Run.log() got an unexpected keyword argument 'pretraining'
